# Generated by Django 3.0.3 on 2020-06-19 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 22, 15, 17, 369237), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 22, 15, 17, 368237), null=True),
        ),
    ]
