# Generated by Django 3.0.3 on 2020-06-17 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 18, 0, 35, 29, 954096), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 18, 0, 35, 29, 952096), null=True),
        ),
    ]
