# Generated by Django 3.0.3 on 2020-06-20 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audible',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 23, 48, 32, 405658), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='kindle',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 23, 48, 32, 404656), null=True),
        ),
    ]
